
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.myfirstapp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSEBRACE = 7;
  public static final int TAG = 20;
  public static final int PERCENT = 32;
  public static final int SEMICOLON = 12;
  public static final int OPENBRACE = 6;
  public static final int DECIMAL = 31;
  public static final int SUMA = 3;
  public static final int CLOSEPAR = 9;
  public static final int MULTI = 4;
  public static final int COLON = 13;
  public static final int OPENPAR = 8;
  public static final int PORCENTAJE = 28;
  public static final int TIPO = 21;
  public static final int VALORES = 24;
  public static final int BARRAS = 15;
  public static final int COMA = 14;
  public static final int TOTAL = 22;
  public static final int EOF = 0;
  public static final int DEF = 27;
  public static final int RUN = 26;
  public static final int PIE = 16;
  public static final int DIV = 5;
  public static final int CANTIDAD = 29;
  public static final int EXTRA = 23;
  public static final int NUMERO = 33;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 11;
  public static final int OPENBRACKET = 10;
  public static final int IDENTIFICADOR = 30;
  public static final int EJEY = 19;
  public static final int EJEX = 18;
  public static final int UNIR = 25;
  public static final int TITULO = 17;
  public static final int RESTA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RESTA",
  "SUMA",
  "MULTI",
  "DIV",
  "OPENBRACE",
  "CLOSEBRACE",
  "OPENPAR",
  "CLOSEPAR",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "SEMICOLON",
  "COLON",
  "COMA",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "TAG",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "VALORES",
  "UNIR",
  "RUN",
  "DEF",
  "PORCENTAJE",
  "CANTIDAD",
  "IDENTIFICADOR",
  "DECIMAL",
  "PERCENT",
  "NUMERO"
  };
}

